module.exports = obj => {
    return {
        contentId: obj.contentId ? obj.contentId._text : null,
        facltNm: obj.facltNm ? obj.facltNm._text : null,
        lineIntro: obj.lineIntro ? obj.lineIntro._text : null,
        intro: obj.intro ? obj.intro._text : null,
        hvofBgnde: obj.hvofBgnde ? obj.hvofBgnde._text : null,
        hvofEnddle: obj.hvofEnddle ? obj.hvofEnddle._text : null,
        featureNm: obj.featureNm ? obj.featureNm._text : null,
        induty: obj.induty ? obj.induty._text : null,
        lctCl: obj.lctCl ? obj.lctCl._text : null,
        doNm: obj.doNm ? obj.doNm._text : null,
        sigunguNm: obj.sigunguNm ? obj.sigunguNm._text : null,
        addr1: obj.addr1 ? obj.addr1._text : null,
        addr2: obj.addr2 ? obj.addr2._text : null,
        direction: obj.direction ? obj.direction._text : null,
        tel: obj.tel ? obj.tel._text : null,
        homepage: obj.homepage ? obj.homepage._text : null,
        exprnProgrm: obj.exprnProgrm ? obj.exprnProgrm._text : null,
        eqpmnLendCl: obj.eqpmnLendCl ? obj.eqpmnLendCl._text : null,
        animalCmgCl: obj.animalCmgCl ? obj.animalCmgCl._text : null,
        tourEraCl: obj.tourEraCl ? obj.tourEraCl._text : null,
        firstImageUrl: obj.firstImageUrl ? obj.firstImageUrl._text : null,
        position: [obj.mapX ? obj.mapX._text : null, obj.mapY ? obj.mapY._text : null],
    }
}